from random import randrange

from kaggle_environments import make, evaluate

from haliteivbot.rule_based.bot import HaliteBot
from haliteivbot.rule_based.bot_tournament import wrap_bot

if __name__ == "__main__":
    genome = {
        "cargo_map_halite_norm": 200,
        "cell_score_dominance": 0.5,
        "cell_score_enemy_halite": 0.25,
        "cell_score_farming": -50,
        "cell_score_danger": 70,
        "cell_score_neighbour_discount": 0.6055250554421567,
        "cell_score_ship_halite": 0.0005,
        "convert_when_attacked_threshold": 493,
        "disable_hunting_till": 60,
        "dominance_map_halite_clip": 70,
        "dominance_map_medium_radius": 5,
        "dominance_map_medium_sigma": 2.846696443002316,
        "dominance_map_small_radius": 3,
        "dominance_map_small_sigma": 1.5624227688652699,
        "early_second_shipyard": 35,
        "end_return_extra_moves": 5,
        "end_start": 382,
        "ending_halite_threshold": 10,
        "farming_end": 355,
        "farming_start": 40,
        "farming_start_shipyards": 2,
        "greed_min_map_diff": 14,
        "greed_stop": 37,
        "guarding_aggression_radius": 3,
        "guarding_end": 375,
        "guarding_max_distance_to_shipyard": 3,
        "guarding_max_ships_per_shipyard": 3,
        "guarding_min_distance_to_shipyard": 1,
        "guarding_norm": 0.6,
        "guarding_radius": 3,
        "guarding_radius2": 1,
        "guarding_ship_advantage_norm": 17,
        "guarding_stop": 342,
        "harvest_threshold_alpha": 0.25,
        "harvest_threshold_beta": 0.34580748711454373,
        "harvest_threshold_hunting_norm": 0.65,
        "harvest_threshold_ship_advantage_norm": 14,
        "hunting_halite_threshold": 0.05,
        "hunting_max_group_distance": 5,
        "hunting_max_group_size": 1,
        "hunting_min_ships": 8,
        "hunting_proportion": 0.435,
        "hunting_proportion_after_farming": 0.35,
        "hunting_score_alpha": 1.1,
        "hunting_score_beta": 0.27,
        "hunting_score_cargo_clip": 1.5,
        "hunting_score_delta": 0.9,
        "hunting_score_farming_position_penalty": 0.8,
        "hunting_score_gamma": 0.98,
        "hunting_score_halite_norm": 210,
        "hunting_score_hunt": 1.8,
        "hunting_score_intercept": 1.4,
        "hunting_score_iota": 0.15,
        "hunting_score_kappa": 0.18,
        "hunting_score_region": 2.8,
        "hunting_score_ship_bonus": 275,
        "hunting_score_ypsilon": 2,
        "hunting_score_zeta": 0.65,
        "hunting_threshold": 11.5,
        "map_blur_gamma": 0.9,
        "map_blur_sigma": 0.40223634381042517,
        "map_ultra_blur": 1.75,
        "max_guarding_ships_per_target": 2,
        "max_halite_attack_shipyard": 0,
        "max_hunting_ships_per_direction": 1,
        "max_intrusion_count": 3,
        "max_ship_advantage": 25,
        "max_shipyard_distance": 8,
        "max_shipyards": 12,
        "min_enemy_shipyard_distance": 4,
        "min_mining_halite": 25,
        "min_ships": 15,
        "min_shipyard_distance": 7,
        "mining_score_alpha": 0.975,
        "mining_score_alpha_min": 0.92,
        "mining_score_alpha_step": 0.007163796627240703,
        "mining_score_beta": 0.98,
        "mining_score_beta_min": 0.95,
        "mining_score_cargo_norm": 3.5,
        "mining_score_dominance_clip": 3.3,
        "mining_score_dominance_norm": 0.4,
        "mining_score_farming_penalty": 0.01,
        "mining_score_gamma": 0.99,
        "mining_score_juicy": 0.28,
        "mining_score_juicy_end": 0.1,
        "mining_score_minor_farming_penalty": 0.15,
        "mining_score_start_returning": 50,
        "minor_harvest_threshold": 0.5883198534618292,
        "move_preference_base": 99,
        "move_preference_block_shipyard": -135,
        "move_preference_constructing": 144,
        "move_preference_construction_guarding": 130,
        "move_preference_guarding": 100,
        "move_preference_guarding_stay": -126,
        "move_preference_hunting": 105,
        "move_preference_longest_axis": 15,
        "move_preference_mining": 125,
        "move_preference_return": 115,
        "move_preference_stay_on_shipyard": -74,
        "return_halite": 860,
        "second_shipyard_min_ships": 8,
        "second_shipyard_step": 12,
        "ship_spawn_threshold": 0.18,
        "ships_shipyards_threshold": 0.175,
        "shipyard_abandon_dominance": -20,
        "shipyard_conversion_threshold": 2.5,
        "shipyard_guarding_attack_probability": 0.35,
        "shipyard_guarding_min_dominance": -15,
        "shipyard_min_dominance": -1,
        "shipyard_min_population": 5,
        "shipyard_min_ship_advantage": -12,
        "shipyard_start": 30,
        "shipyard_stop": 285,
        "spawn_min_dominance": -6.0,
        "spawn_till": 285,
        "third_shipyard_min_ships": 17,
        "third_shipyard_step": 38,
        "trading_start": 120,
    }

    def run_game():
        agent_count = 4
        env = make("halite", configuration={"size": 21}, debug=True)
        env.configuration["randomSeed"] = randrange((1 << 32) - 1)
        info = env.reset(agent_count)
        bot1 = HaliteBot(genome)
        bot2 = HaliteBot(genome)
        results = evaluate(
            "halite",
            [
                wrap_bot(bot1),
                "haliteivbot/evolutionary/bots/uninstalllol3.py",
                wrap_bot(bot2),
                "haliteivbot/evolutionary/bots/uninstalllol3.py",
            ],
            env.configuration,
        )[0]

    run_game()
